version: "3.8"
services:
  surfwiz-db:
    container_name: surfwiz-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=surfwiz
      - POSTGRES_PASSWORD=surfwizpass
      - POSTGRES_DB=surfwizdb
    volumes:
      - surfwiz-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U surfwiz -d surfwizdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  surfwiz-data:
    name: surfwiz-data
